### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Dhivin** [PilzDE/psen_scan#30]
![image](https://user-images.githubusercontent.com/16065551/86074801-3474b000-bab9-11ea-9638-e64a415b0659.png)

Has anyone noticed the high CPU usage while running psen_scan?

**Comment by saheinisch** [comment]
Hello Dhivin,

to clarify this issue I need more information. 
* What machine is used to run the software?
* Are there other processes running which consume CPU ressources?
* Does the psenscan driver print error messages in the terminal?

**Comment by Dhivin** [comment]
> Hello Dhivin,
> 
> to clarify this issue I need more information.
> 
>     * What machine is used to run the software?
> 
>     * Are there other processes running which consume CPU ressources?
> 
>     * Does the psenscan driver print error messages in the terminal?

What machine is used to run the software?
_I am running it on a i7 CPU (4 cores)_

Are there other processes running which consume CPU resources?
_No.I am only running 2 instances of PSEN scan. Front laser and back laser._

Does the psenscan driver print error messages in the terminal?
_No it does not._

**Comment by jschleicher** [comment]
@Dhivin Thank you very much for your report. I can reproduce the issue here. We will have a look into it and come up with a fix as soon as possible. We hope to release it into the next sync for ROS melodic which usually happens in approx. three weeks.

We are sorry for any inconvenience this may have caused.
